#' Get the cluster and membership information
#'
#' @param data.mean a matrix from grp.mean function
#' @param fcmc the result of ggfcmc function
#' @param write a boolean value, save the result or not
#'
#' @return a data frame
#' @export
#'
#' @author Zhonghui Gai
#' @examples
#' fcmc.df(data.mean = genus.syn.mean, fcmc = fcmc, write = F)
fcmc.df <- function(data.mean, fcmc, write = TRUE){
  if (!inherits(data.mean, "grp.mean")) {
    stop("the input data.mean must be the class of 'grp.mean', which is generated by grp.mean function")
  }
  if (!inherits(fcmc, "fclust")) {
    stop("the input fcm must be the class of 'fclust', which is generated by ggfcmc function")
  }
  fcm <- fcmc$cluster
  if (all(rownames(data.mean) == rownames(fcm))) {
    df <- cbind(genus.syn.mean, cluster = fcm)
    df <- as.data.frame(df)
    df$membership <- sapply(1:length(fcm), function(row) {
      clust <- fcm[row]
      fcmc$membership[row, clust]
    })
  }else{
    stop("The names of data.mean and fcmc are not identical!")
  }
  if (write) {
    write.table(df, file = "mean.cluster.result.txt", sep = "\t")
  }else{
    print(df)
  }
}
